linters-settings:
  lll:
    line-length: 180
linters:
  enable-all: true
  disable:
    - testpackage
    - forbidigo
    - paralleltest
    - varnamelen
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    - exhaustruct
    - nolintlint
    - wrapcheck
    - depguard
    - gomnd
    - execinquery
    - exportloopref