name: goreleaser

on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}

permissions:
  contents: write
  packages: write
  id-token: write
  attestations: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: ghcr-login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Attest package provenance
        uses: actions/attest-build-provenance@v1
        with: 
          subject-path: |
            dist/*.apk
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.zip
      -
        name: Attest container provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ghcr.io/${{ github.repository }}
          push-to-registry: true
